version: '3.9'

services:

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    
    container_name: fakeapirest
    command: sh -c "./start.sh"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mysql
  
  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    container_name: mysqldatabase
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=fakeapirest
      - MYSQL_USER=mysql_api
      - MYSQL_PASSWORD=12345678
      - MYSQL_ROOT_PASSWORD=rootpassword

volumes:
  mysql_data:
